.\"		-*-Nroff-*-
.\" Copyright 2000 Red Hat, Inc.
.TH VNCCONNECT 1 "6 Nov 2000"
.SH NAME
vncconnect \- connect a VNC server to a VNC viewer
.SH SYNOPSIS
.nf
\fBvncconnect\fR [\-display \fIXvnc-display\fR] \fIhost\fR[:\fIport\fR]
.fi
.SH DESCRIPTION
Tells \fBXvnc\fR(1) to connect to a listening VNC viewer on the given
host and port.
.SH SEE ALSO
\fBvncviewer\fR(1), \fBvncserver\fR(1), \fBXvnc\fR(1), \fBvncpasswd\fR(1)
.SH AUTHOR
AT&T Laboratories Cambridge
.br
Man page by Tim Waugh <twaugh@redhat.com>
