.\"		-*-Nroff-*-
.\" Copyright 2000 Red Hat, Inc.
.TH VNCPASSWD 1 "6 Nov 2000"
.SH NAME
vncpasswd \- set password for VNC server
.SH SYNOPSIS
.nf
\fBvncpasswd\fR [\fIfile\fR]
.fi
.SH DESCRIPTION
Set a VNC password.  This is used for setting a password for use by
\fBXvnc\fR(1).  By default it will store this in
\fB$HOME/.vnc/passwd\fR.
.SH SEE ALSO
\fBvncviewer\fR(1), \fBvncserver\fR(1), \fBXvnc\fR(1), \fBvncconnect\fR(1)
.SH AUTHOR
AT&T Laboratories Cambridge
.br
Man page by Tim Waugh <twaugh@redhat.com>
